name: Deploy Website
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/jurutani.com
            git pull origin main
            pnpm install
            pnpm build
            pm2 restart jurutani || pm2 start .output/server/index.mjs --name jurutani
